model_config:
  model_name: microsoft/phi-2
  model_kwargs:
    pretrained_model_name_or_path: microsoft/phi-2
    trust_remote_code: True
    device_map: auto
    cache_dir: _cache_models/

dataset_config:
  dataset_name: gsm8k
  dataset_kwargs:
    path: gsm8k
    name: main
    split: test
    cache_dir: _cache_data/

prompt_config:
  prompt_name: GSM8K_COT_FEWSHOT

generation_kwargs:
  max_new_tokens: 200
  do_sample: False

until:
  - "Question:"
  - "Question: "
  - "\n\n"
  - "Q: "

batch_size: 4
padding_size: left
truncation: False
seed: 0
results_fn: results.json
device: cuda
limit: 20